name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: theta-idl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build haskell
        run: nix-build theta

      - name: cross-language tests
        run: nix-build test

      - name: Stack test
        run: |
          nix-shell
          cd theta
          stack --nix --nix-shell-file stack-shell.nix test
