name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: theta-idl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Theta
        run: nix-build theta

      - name: Cache Stack Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('theta/stack.yaml.lock', 'theta/theta.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack

      - name: Stack Test
        run: ci/stack-test ./theta

      - name: Cross-Language Tests
        run: nix-build test
